# -*- coding: utf-8 -*-
"""Quotes to scrape.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1D4VJ7NOmLdoOiRZk_s1pjlALJyRMXp
"""

pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/"

response = requests.get(url)
print("Respnse status code: ", response.status_code)
print("Response Content: ")
print(response.text)

soup = BeautifulSoup(response.text, 'html.parser')
print(soup.prettify)

header = soup.find('h1')
print("Header: ", header.text)

quotes = soup.find_all('span', class_='text')
print("Quotes: ")
for quote in quotes:
    print(quote.text)